name: yolov8_onnx
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - conda-forge::gxx_linux-aarch64
  - pip
  - numpy<1.23
  - pip:
    - opencv-python==4.7.0.72
    - scipy==1.10.1
    - lap==0.4.0
